content:
  - name: docs
    label: Docs
    type: collection
    path: docs
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
