content:
  - name: docs
    label: Dokümantasyon
    type: collection
    path: docs
    extension: md

    fields:
      - name: title
        label: Başlık
        type: string
        required: true

      - name: body
        label: İçerik
        type: rich-text

